name: CommandTree-API
main: org.kanelucky.core.CommandTreeMain
version: "0.1.0"
api: "2.0.0"
author: Kanelucky
description: A lightweight library that provides a modern command tree API for PowerNukkitX
website: https://github.com/Kanelucky/CommandTree